import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import PageWrapper from "@/components/templates/wrappers/pageWrapper";
import { Inter } from "next/font/google";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import AuthWrapper from "@/components/templates/wrappers/authwrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <AuthWrapper>
        <head>
          <ColorSchemeScript />
        </head>
        <body className="overflow-hidden">
          <MantineProvider>
            <PageWrapper>
              {children}
            </PageWrapper>
          </MantineProvider>
          <Toaster />
        </body>
      </AuthWrapper>
    </html>
  );
}
